// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDecpTPrVn4Zx7FP2w-43W4iuY7XbynEMc',
    appId: '1:651442032096:web:47bcfbd7cf3d2002676f85',
    messagingSenderId: '651442032096',
    projectId: 'cordoplan-uco',
    authDomain: 'cordoplan-uco.firebaseapp.com',
    storageBucket: 'cordoplan-uco.firebasestorage.app',
    measurementId: 'G-2RLRHDYJVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx4xbXGMqjzXp46MYgwFLlyny5SSPuBEo',
    appId: '1:651442032096:android:077b622db7002a8f676f85',
    messagingSenderId: '651442032096',
    projectId: 'cordoplan-uco',
    storageBucket: 'cordoplan-uco.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC37gdO2UfG5X1iJfxwIL7ao0K0oF2x1IE',
    appId: '1:651442032096:ios:eecbe5507d3accb4676f85',
    messagingSenderId: '651442032096',
    projectId: 'cordoplan-uco',
    storageBucket: 'cordoplan-uco.firebasestorage.app',
    iosBundleId: 'com.example.cordoplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC37gdO2UfG5X1iJfxwIL7ao0K0oF2x1IE',
    appId: '1:651442032096:ios:eecbe5507d3accb4676f85',
    messagingSenderId: '651442032096',
    projectId: 'cordoplan-uco',
    storageBucket: 'cordoplan-uco.firebasestorage.app',
    iosBundleId: 'com.example.cordoplan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDecpTPrVn4Zx7FP2w-43W4iuY7XbynEMc',
    appId: '1:651442032096:web:34040b8ea557e9b4676f85',
    messagingSenderId: '651442032096',
    projectId: 'cordoplan-uco',
    authDomain: 'cordoplan-uco.firebaseapp.com',
    storageBucket: 'cordoplan-uco.firebasestorage.app',
    measurementId: 'G-50QTM2FRBF',
  );

}